module.exports = 
{

	//full urls
	
	full: {
		"eyecareplus" : ["lifestyle", "health", "eyes"],
		"dating.birminghammail" : ["lifestyle", "dating"],
		"birminghammail": ["information", "news", "regional"],
		"mailcashback":["support", "shopping", "cashback"],
		"callforparticipants":["participation"],
		"visualdna":["participation", "profiling"],
		"ucnproject":["participation", "data collection"],
		"toluna":["participation", "surveys"],
		"yourword":["participation", "surveys"],
		"thinkindia":["participation", "policy", "indian"],
		
		"yougov.co.uk":["information", "government"],
		"ycharts.com":["support", "tools", "research", "financial"],
		"yandex.ru":["support", "search engine"],
		"yahoo.net":["support", "search engine"],
		"www2.smartbrief.com":["information", "news", "industry"],
		"www.zoneoneradio.com": ["entertainment", "streaming", "music"],
		"www.yoyo.com": ["support", "shopping", "children", "toys"],
		"www.wymans.com":["lifestyle", "food", "healthy eating"],
		"www.worldcat.org":["information", "library"],
		"www.weibo.com": ["communication", "blog"],
		"www.webcourseworks.com":["support", "learning resources"],
		"www.walmart.com":["support", "shopping", "supermarket"],
		"www.vocativ.com":["entertainment", "magazine", "technology and media"],
		"www.vasantvalley.org":["information", "school"],
		"www.ursongspk.com":["entertainment", "streaming", "music"],
		"www.ukcisa.org.uk":["information", "university", "international students"],
		"www.ubuonline.co.uk":["information", "university", "student union"],
		"www.trynewperfumes.com":["participation", "product sampling"],
		"www.trickybet.net": ["lifestyle", "gambling"],
		"www.trendingfirst.co.uk":["entertainment", "magazine", "technology and media"],
		"www.trademarkencyclopedia.com":["information", "trademarks"],
		"www.top-employers.com":["information", "jobs"],
		"www.timetobreak.com":["entertainment", "interest", "celebrity"],
		"www.thevalueperspective.co.uk":["information", "finance", "investment"], 
		"www.theflystudio.com":["support", "digital media", "web design"],
		"www.thecampusprogram.org":["support", "student", "mental health"],
		"www.thebrofessional.net":["entertainment", "interest", "celebrity"],
		"www.thebrightsidetrust.org":["support", "mentoring"],
		"www.theartisanbistro.com":["lifestyle", "food"],
		"www.the-network.com":["information", "jobs"],
		"www.tentopi.com":["entertainment", "interest", "celebrity"],
		"www.tedbakerplc.com":["support", "shopping", "clothes"],
		"www.tedbaker.com":["support", "shopping", "clothes"],
		"www.td.org":["information", "career development"],
		"www.tandfonline.com":["information", "academic"],
		"www.tagoras.com":["support", "learning resources"],
		"www.swlearning.com":["support", "learning resources"],
		"www.stockplanconnect.com":["support", "tools", "research", "financial"],
		"www.stata.com":["support", "tools", "stats"],
		"www.springer.com":["information", "academic"],
		"www.speakingtree.in":["lifestyle", "astrology"],
		"www.softworld.co.uk":["information", "jobs"],
		"www.smuckers.com":["lifestyle", "food","food product"],
		"www.smartbrief.com":["information", "news", "industry"],
		"www.sipc.org":["information", "finance", "investment", "protection"],
		"www.simplyorganic.com":["lifestyle", "food", "recipes"],
		"www.sikhi.sm":["lifestyle", "religion", "sikhism"],
		"www.sephora.com":["support", "shopping", "beauty"],
		"www.scopus.com":["information", "academic"],
		"www.schweser.com":["information", "courses", "financial certification"],
		"www.savingschampion.co.uk":["information", "money saving"],
		"www.saveur.com":["lifestyle", "food"],
		"www.sas.com":["support", "tools" , "analytics"],
		"www.sapub.org":["information", "academic"],
		"www.sadc.int":["information", "african development"],
		"www.riskglossary.com":["information", "finance", "risk"],
		"www.reports.dianomioffers.co.uk":["information", "reports"],
		"www.regalcreative.com":["support", "digital media"],
		"www.reedglobal.com":["information", "jobs"],
		"www.reedcommercial.com":["information", "jobs"],
		"www.redonline.co.uk":["entertainment", "magazine", "womens"],
		"www.rediff.com": ["information", "news", "india"],
		"www.realclearworld.com":["information", "news"],
		"www.realclear.com":["entertainment", "magazine", "humour"],
		"www.rd-india.com":["entertainment", "magazine"],
		"www.qtsnumeracytest.co.uk":["support", "learning resources", "tests", "numeracy"],
		"www.psychtesting.org.uk":["support","learning resources",  "tests", "psychometric"],
		"www.prweb.com":["information", "news", "public relations"],
		"www.prevention.com":["lifestyle", "health"],
		"www.placement-uk.com":["information", "placements"],
		"www.phpbb.com":["support", "tools", "bulletin board"],
		"www.pearsonschoolsandfecolleges.co.uk":["information", "courses"],
		"www.pearsonhighered.com":["information", "courses"],
		"www.pawsaminute.net":["entertainment", "interest", "dogs"],
		"www.passtheqtsskillstests.co.uk":["support", "learning resources", "tests", "qts"],
		"www.parisattitude.com":["support", "travel", "destination", "paris"],
		"www.paloalto.com":["support", "tools", "business planning"],
		"www.paidproducttesting.co.uk":["participation", "product sampling"],
		"www.paidfocusgroup.co.uk":["participation", "focus group"],
		"www.paconsulting.com":["information", "consulting"],
		"www.oyorooms.com":["support", "travel", "destination", "india"],
		"www.organicvalley.coop":["lifestyle", "food","food product"],
		"www.orderannualreports.com":["information", "reports"],
		"www.onrec.com":["information", "jobs"],
		"www.nytwineclub.com":["lifestyle", "food", "wine"],
		"www.nytco.com":["information","news"],
		"www.nutsonline.org":["entertainment", "tv", "student tv"],
		"www.nseindia.com":["information", "finance", "investment"],
		"www.nottsvarsity.co.uk":["lifestyle", "sport"],
		"www.nottinghamtec.co.uk":["information", "audio equipment"],
		"www.netetudes.com":["participation", "surveys"],
		"www.nasoya.com":["lifestyle", "food", "food product"],
		"www.nao.org.uk":["information", "finance", "auditing"],
		"www.myspace.com":["communication", "social networking"],
		"www.myhabit.com":["support", "shopping", "clothes"],
		"www.mydearvalentine.com":["lifestyle", "dating"],
		"www.mvmtwatches.com":["support", "shopping", "watches"],
		"www.msn.com":["support", "search engine"],
		"www.mrsite.com":["support", "tools", "website builder"],
		"www.mplans.com":["information", "marketing"],
		"www.moonflowerdesign.net":["support", "digital media", "web design"],
		"www.mooch-bar.co.uk":["lifestyle", "food", "restaurant"],
		"www.momondo.co.uk":["communication", "blog"],
		"www.meridianks.com":["support", "learning resources"],
		"www.mercola.com":["lifestyle", "health"],
		"www.mercer.com":["information", "finance"],
		"www.maxwrapup.com":["entertainment", "magazine", "mens"],
		"www.mansionglobal.com":["lifestyle", "luxury", "luxury property"],
		"www.macrothink.org":["information", "academic"],
		"www.m2k.me":["entertainment", "streaming", "films"],
		"www.lseg.com":["information", "finance", "investment"],
		"www.look.com":["support", "shopping", "children", "clothes"],
		"www.londonstockexchange.com":["information", "finance", "investment"],
		"www.londonperfect.com":["support", "travel", "destination", "paris"],
		"www.liveplans.com":["support", "tools", "business planning"],
		"www.liveplan.com":["support", "tools", "business planning"],
		"www.literallydarling.com":["entertainment", "magazine", "womens"],
		"www.kusumatrust.org":["information", "charity", "childrens education"],
		"www.kingarthurflour.com":["lifestyle", "food", "food product"],
		"www.karger.com":["information", "academic"],
		"www.junglee.com":["support", "classifieds"],
		"www.jstor.org":["information", "academic"],
		"www.jprime.com":["information", "finance", "investment"],
		"www.jlr.org":["information", "academic", "lipids"],
		"www.jlcre.com":["information", "finance", "realestate"],
		"www.jitsufoundation.org":["lifestyle", "health", "fitness", "jiu jitsu"],
		"www.jefferies.com":["information", "finance", "investment"],
		"www.iza.org":["information", "academic", "labor"],
		"www.ivoryresearch.com":["support", "coursework or exams"],
		"www.ireland.com":["support", "travel","destination", "ireland"],
		"www.ipoll.com":["participation", "surveys"],
		"www.iovs.org":["information", "academic", "opthalmology"],
		"www.intergrad.co.uk":["information", "jobs"],
		"www.insidehighered.com":["information", "news", "higher education"],
		"www.infobase.co.in":["support", "digital media", "web design"],
		"www.india-forums.com":["communication", "forum"],
		"www.independentsubscriptions.co.uk":["information", "news"],
		"www.incisivemedia.com":["information", "finance", "business"],
		"www.impactnottingham.com":["entertainment", "magazine", "student union"],
		"www.imdb.com":["entertainment", "films"],
		"www.imanet.org":["information","finance", "accounting"],
		"www.hp.com": ["information", "computers", "hardware"],
		"www.hindawi.com":["information", "academic"],
		"www.highfliers.co.uk":["information", "jobs"],
		"www.hertfordshiremercury.co.uk": ["information", "news", "regional"],
		"www.hbrsasia.org":["information", "finance", "business"],
		"www.harpersbazaar.co.uk":["entertainment", "magazine", "womens"],
		"www.graphpad.com":["support", "tools", "graphing"],
		"www.gq-magazine.co.uk":["entertainment", "magazine", "mens"],
		"www.gossipedge.com":["entertainment", "interest", "celebrity"],
		"www.goodreads.com": ["communication", "social networking", "reading"],
		"www.golfdigestindia.com":["lifestyle", "sport", "golf"],
		"www.gleems.com":["entertainment", "interest", "cars"],
		"www.glassdoor.co.uk":["information", "jobs"],
		"www.girlinlondon.com":["communication", "blog"],
		"www.geoplugin.net":["support", "tools", "plugin"],
		"www.gdst.net":["information", "school"],
		"www.gadgetsngizmos.in":["information", "news", "technology"],
		"www.fuzzfix.com":["entertainment", "magazine", "animals"],
		"www.furl.net":["support", "bookmarks"],
		"www.ftse.com":["information", "finance", "investment"],
		"www.fow.com":["information", "finance", "investment"],
		"www.fotor.com":["support", "tools", "photo editor"],
		"www.flavourjournal.com":["information", "academic", "flavour"],
		"www.findcpd.com":["information", "courses", "continuing professional development"],
		"www.fidelityinternational.com":["information", "finance", "investment"],
		"www.fca.org.uk":["information", "finance", "financial conduct"],
		"www.famefocus.com":["entertainment", "interest", "celebrity"],
		"www.exinfm.com":["information", "finance", "financial management"],
		"www.eventbrite.co.uk":["support", "tickets"],
		"www.eurolines.co.uk":["support", "travel", "coach"],
		"www.eurekaselect.com":["information", "academic", "science"],
		"www.espn.co.uk":["lifestyle", "sport"],
		"www.emolument.com":["information", "jobs"],
		"www.elsevier.com":["information", "academic"],
		"www.elearninglearning.com":["support", "learning resources"],
		"www.efficientlearning.com":["support", "learning resources"],
		"www.edenred.co.uk":["information", "finance"],
		"www.economist.com":["information", "news"],
		"www.econometrics.com":["support", "tools", "stats"],
		"www.e2eresearch.com":["support", "market research"],
		"www.dpreview.co.uk":["information", "news", "technology", "digital camera"],
		"www.diva-portal.org":["information", "academic"],
		"www.directions.org.uk":["information", "jobs"],
		"www.dipintosales.co.uk":["support", "shopping", "photo printing"],
		"www.digitalistmag.com":["information", "marketing"],
		"www.diapers.com":["support", "shopping", "children", "clothes"],
		"www.deshaw.com":["information", "finance", "investment"],
		"www.deepdyve.com":["information", "academic"],
		"www.db.com":["information", "finance",  "banking"],
		"www.danahotyoga.com":["lifestyle", "sport", "yoga"],
		"www.dailyo.in":["entertainment", "magazine"],
		"www.crystalski.co.uk":["lifestyle", "sport", "skiing"],
		"www.createspace.co.uk":["support", "tools", "self publish"],
		"www.crainsnewyork.com":["entertainment", "magazine"],
		"www.cpareviewforfree.com":["support", "learning resources", "coursework or exams"],
		"www.coursework4you.co.uk":["support", "learning resources",  "coursework or exams"],
		"www.coursehero.com":["support", "learning resources", "coursework or exams"],
		"www.copyright.com":["information", "copyright"],
		"www.convertiblebonds.ch":["information", "finance", "investment"],
		"www.cmo.com":["information", "marketing"],
		"www.cloudy.ec":["entertainment", "streaming", "video"],
		"www.cloudpro.co.uk":["information", "news", "technology"],
		"www.civicuk.com":["support", "digital media"],
		"www.city-data.com":["support", "tools", "data repository"],
		"www.citeulike.org":["support", "bookmarks"],
		"www.cimaondemand.com":["information", "cpd"],
		"www.cii.co.uk":["information", "finance"],
		"www.chicmodern.co.uk": ["entertainment", "magazine", "womens"],
		"www.chevening.org":["information", "scholarships"],
		"www.cheapflights.ca":["support", "travel", "air"],
		"www.channelpro.co.uk":["information", "news", "technology"],
		"www.cgma.org":["information","finance", "accounting"],
		"www.cfainstitute.org":["information", "courses", "professional"],
		"www.capco.com":["information", "finance"],
		"www.c2c-online.co.uk":["support", "travel", "rail"],
		"www.buzzaura.com":["entertainment", "interest", "celebrity"],
		"www.buyvip.com":["support", "shopping"],
		"www.burton.co.uk":["support", "shopping", "menswear"],
		"www.brightknowledge.org":["information", "jobs"],
		"www.breadcreative.com":["support", "digital media"],
		"www.bplans.com":["support", "tools", "business planning"],
		"www.bp.com":["information", "fuel and transport"],
		"www.bg-removals.co.uk":["support", "removals and storage"],
		"www.bellandevans.com":["lifestyle", "food", "food product"],
		"www.bdo.com":["information", "finance", "business"],
		"www.barneys.com":["support", "shopping", "beauty"],
		"www.bap.org":["communication", "social networking", "students"],
		"www.aviva.co.uk":["support", "insurance"],
		"www.attractiontix.co.uk":["support", "tickets", "attractions"],
		"www.assignmentwritinghelp.com":["support", "learning resources", "coursework or exams"],
		"www.ascentive.com":["support", "tools", "computer performance"],
		"www.aquarico.com":["information", "consulting"],
		"www.apartmenttherapy.com":["lifestyle", "home"],
		"www.apa.org":["information", "psychology"],
		"www.aon.com":["information", "finance", "risk"],
		"www.aon.co.uk":["information", "finance", "risk"],
		"www.aon-onboarding.co.uk":["information", "jobs"],
		"www.angloamerican.com":["information", "fuel and transport"],
		"www.analystforum.com":["support", "learning resources", "coursework or exams"],
		"www.amosweb.com":["information", "finance"],
		"www.amd.com":["information", "news", "technology", "processor"],
		"www.ahzassociates.co.uk":["support", "student"],
		"www.agcas.org.uk":["information", "jobs"],
		"www.acx.com":["support", "tools", "audiobook creator"],
		"www.activeminds.org":["support", "student", "mental health"],
		"www.activebeat.com":["lifestyle", "food", "healthy eating"],
		"www.accidentadvicehelpline.co.uk":["support", "accident advice"],
		"www.aabri.com":["information", "academic", "business research"],
		"www.aabestemployer.co.uk":["information", "jobs"],
		"www.123helpme.com":["support","learning resources",  "coursework or exams"],
		"wu.ac.at":["information", "university"],
		"weheartit.com":["communication", "social networking", "photos"],
		"wanderingpioneer.com":["lifestyle", "travelling"],
		"voteview.com":["information", "political science"],
		"vitamind.mercola.com":["lifestyle", "health"],
		"viralvinny.com":["entertainment", "interest", "celebrity"],
		"vine.co": ["entertainment", "streaming", "video"],
		"viewmixed.com":["entertainment", "interest", "celebrity"],
		"vidshare.us":["entertainment", "streaming", "video"],
		"vaccines.mercola.com":["lifestyle", "health"],
		"uwasa.fi":["information", "university"],
		"uk.yahoo.com":["support", "search engine"],
		"uk.screen.yahoo.com":["support", "search engine"],
		"uk.safely.yahoo.com":["information", "computers", "safety and privacy"],
		"uk.mobile.yahoo.com":["support", "apps"],
		"uk.messenger.yahoo.com":["communication", "instant messaging"],
		"uk.mercer.com":["information", "finance", "investment"], 
		"uk.help.yahoo.com":["support", "search engine"],
		"uk.groups.yahoo.com": ["communication", "forum"],
		"uk.everything.yahoo.com":["support", "search engine"],
		"uk.easyroommate.com":["support", "accommodation"],
		"uk.dice.com":["information", "jobs"],
		"uberhavoc.com":["entertainment", "magazine", "humour"],
		"uam.es":["information", "university"],
		"tradefx.com":["information", "finance", "investment"], 
		"tmdb.org":["entertainment", "films"],
		"thirtythreeweb.co.uk":["communication", "email"],
		"thetab.com":["information", "news"],
		"theologyphilosophycentre.co.uk":["information", "theology"],
		"theconversation.com":["information","news"],
		"thebigchoice.com":["information", "jobs"],
		"tablesorter.com":["support", "tools", "table sorter"],
		"suitcasemag.com":[ "lifestyle", "travelling"],
		"stumble-upon.com":["communication", "social networking", "link sharing"],
		"stockfuse.com":["support", "tools", "virtual trading"],
		"statext.com":["support", "tools", "stats"],
		"squarespace.com":["support", "tools", "website builder"],
		"soletshangout.com": ["lifestyle", "food", "healthy eating"],
		"software.instant-income-app.com":["support", "tools", "trading"],
		"snoutit.com":[ "lifestyle", "travelling"],
		"smmc.squarespace.com":["support","learning resources",  "statistics"],
		"sharemasterindia.com": ["information", "finance", "investment"],
		"sellfy.com":["support", "tools", "digital marketplace"],
		"securetrk.co.uk":["support", "tools", "digital marketing"],
		"sciverse.com":["information", "academic"],
		"schoolleavers.mazars.co.uk":["information", "jobs"],
		"sayedhossain.com":["information", "courses"],
		"sappartneredge.com":["information", "business management"],
		"sap.com":["information", "business management"],
		"qz.com":["information", "news"],
		"psl.com":["support","learning resources",  "tests"],
		"principlesofeconometrics.com":["support", "learning resources", "econometrics"],
		"preventionindia.in":[ "lifestyle", "health"],
		"prbb.org":["information", "university"],
		"polldaddy.com":["support", "tools", "polling and surveys"],
		"planningcommission.nic.in":["information", "government", "regional development"],
		"pes.org.ph":["information", "economics", "philippines"],
		"pages.rediff.com":["communication", "social networking", "link sharing"],
		"owlgraphic.com":["support", "tools", "client javascript"],
		"ow.ly":["support", "tools", "url shortener"],
		"openload.co":["support", "tools", "file sharing"],
		"olinwustl.campusgroups.com":["information", "university"],
		"nytedu.com":["information", "courses"],
		"nyt.com":["information", "news"],
		"nxbus.co.uk":["support", "travel", "coach"],
		"nomnompaleo.com": ["lifestyle", "food", "recipes"],
		"nlreg.com":["support", "tools", "stats"],
		"newtheatre.org.uk":["lifestyle", "arts", "theatre"],
		"metro.co.uk":["information", "news"],
		"mercury.mercola.com":["lifestyle", "health", "dentistry"],
		"mazars.co.uk":["information","finance", "accounting"],
		"mathworld.wolfram.com":["support", "learning resources", "mathematics"],
		"mandrillapp.com":["communication", "email"],
		"mackeeper.com":["support", "tools", "computer performance"],
		"luxurybeyondproduct.com":["lifestyle", "luxury"],
		"livesimply.me":["lifestyle", "food", "recipes"],
		"lipas.uwasa.fi":["information", "university"],
		"letwatch.us":["entertainment", "streaming", "video"],
		"learneconometrics.com":["support", "learning resources",  "econometrics"],
		"labs.rediff.com":["information", "infographics"],
		"kerrygoldusa.com":["lifestyle", "food", "food product"],
		"karalydon.com":["lifestyle", "food", "healthy eating"],
		"ishare.rediff.com":["entertainment", "streaming", "video"],
		"instant-income-app.com":["support", "tools", "trading"],
		"inkandwater.co.uk":["support", "digital media"],
		"independent.touchlocal.com":["support", "recommendations", "businesses"],
		"hubspot.com":["support", "tools", "digital marketing"],
		"hereisthecity.com":["information", "finance", "business"],
		"greatist.com":["lifestyle","health"],
		"gfk.com":["information", "finance", "business"],
		"gazefree.com":["entertainment", "streaming", "video"],
		"fullthrottlelegends.com":["entertainment", "interest", "cars"],
		"fructose.mercola.com":["lifestyle", "health", "fructose"],
		"freshstartineducation.co.uk":["support", "student"],
		"fluoride.mercola.com":["lifestyle", "health", "fluoride"],
		"flatworldknowledge.com":["support", "learning resources"],
		"fitness.mercola.com":["lifestyle", "health", "fitness"],
		"fidelity.co.uk":["information", "finance", "investment"],
		"events.qz.com":["information", "events"],
		"europa.eu":["information", "european union"],
		"esri.com":["support", "tools", "maps"],
		"elearningfeeds.com":["support", "learning resources"],
		"ejbe.org":["information", "academic", "business research"],
		"do-it.org":["participation", "volunteering"],
		"digg.com":["entertainment", "magazine", "technology and media"],
		"dice.com":["information", "jobs"],
		"creativecommons.org":["support", "digital content"],
		"corporate.morningstar.com":["information", "finance", "investment"],
		"cookieandkate.com":["lifestyle", "food", "recipes"],
		"compensationinsider.com":["information", "finance"],
		"commerce.rediff.com":["support", "shopping"],
		"cancer.mercola.com":["lifestyle", "health", "cancer"],
		"campus.bankofamerica.com":["information", "jobs"],
		"bragg.com":["lifestyle", "food", "healthy eating"],
		"borsaitaliana.it":["information", "finance", "investment"],
		"boreburn.com":["entertainment", "interest", "celebrity"],
		"bodyos.me":["lifestyle", "food", "recipes"],
		"blueimp.github.io":["support", "tools", "client javascript"],
		"bakingbites.com":["lifestyle", "food", "recipes"],
		"aw.com":["support", "learning resources"],
		"articles.mercola.com":["lifestyle", "health"],
		"articles.bplans.com":["support", "tools", "business planning"],
		"apester.com":["support", "digital media"],
		"animalmozo.com": ["entertainment", "magazine", "animals"],
		"alltop.com":["information", "news", "technology"],
		"adventurecrunch.com":["entertainment", "magazine", "humour"],
		"aaapubs.org":["information", "academic", "accounting research"],
		"localworld.co.uk":["information", "news"],
		"www.eatclean.com":["lifestyle", "food", "healthy eating"],
		"examine.com":["lifestyle", "health"],
		"nationalexpress":["information", "travel"],
		"cooking.nytimes.com":["lifestyle", "food", "recipes"],
		"puzzles.independent.co.uk": ["entertainment", "interest", "puzzles"],
		"casino.telegraph" : ["lifestyle", "gambling"],
		"tickets.independent.co.uk": ["support", "tickets"],
		"tickets.telegraph.co.uk": ["support", "tickets"],
		"www.accountingtoday.com": ["information","finance", "accounting"],
		"www.autoexpress.co.uk": ["entertainment", "interest", "cars"],
		"www.americanexpress.com":["support", "bank", "credit card"],
		"www.bagittoday.com":["support", "shopping"],
		"www.caretoday.in":["information", "charity"],
		"soulmates.theguardian.com":["lifestyle", "dating"],
		"weather.thesun.com":["information", "weather"],
		"classifieds.nottinghampost.com":["information", "classifieds"],
		"rodalenews":["lifestyle", "food"],
		"www.postgrad.com":["information", "courses", "doctorate"],
		"www.findapostdoc.com":["information", "courses", "doctorate"],
		"timesofmoney":["support", "ecommerce"],
		"voucherexpress":["support", "shopping"],
		"www.thomsonpress.com":["support","commercial printing"],
		"studiopress":["support", "tools", "wordpress plugins"],
		"luxpresso.com":["lifestyle", "luxury"],
		"indianexpress.com":["information", "news", "india"],
		"www.pressroomvip.com":["entertainment", "magazine", "humour"],
		"yahoo.com":["support", "search engine"],
		"youqueen.com":["entertainment", "magazine", "womens"],
		"www.wolfson.org.uk":["information", "charity", "science and medicine"],
		"www.warwickschool.org":["information", "school"],
		"www.warwickretail.com":["support", "shopping", "university campus"],
		"www.warwickartscentre.co.uk":["lifestyle", "arts"],
		"www.warwick.in":["information", "university"],
		"www.warwick.com.hk":["information", "university"],
		"www.warwick.ac.ru":["information", "university"],
		"www.visitwesthollywood.com":["support", "travel", "destination", "west hollywood"],
		"www.ubu.org.uk":["information", "university"],
		"www.toysrus.co.uk":["support", "shopping", "children", "toys"],
		"www.thersa.org":["information", "foundation", "societal change"],
		"www.test.com":["support", "learning resources", "tests"],
		"www.suttontrust.com":["information", "charity", "social mobility"],
		"www.statschat.org.nz":["communication", "blog", "stats analysis"],
		"www.ssrn.com":["information", "academic", "social science"],
		"www.shirazcuisine.co.uk":["lifestyle", "food"],
		"www.shahcaterings.co.uk":["lifestyle", "food"],
		"www.seriouswebsupport.com":["support", "digital media", "web design"],
		"www.schoolwebsite.co.uk":["support", "digital media", "web design"],
		"www.sagepay.com":["support", "ecommerce"],
		"www.royal-oak.org":["information", "charity", "historical buildings"],
		"www.ronaldjanki.com":["communication", "blog", "philosophy and poetry"],
		"www.researchgate.net":["information", "academic"],
		"www.readcube.com":["information", "academic"],
		"www.rashmee.com":["communication", "blog", "current affairs"],
		"www.quandl.com":["support", "tools", "stats"],
		"www.premierit.com":["support", "learning resources"],
		"www.prd.copyright.com":["information", "copyright"],
		"www.onlineregister.com":["support", "tools", "product registration"],
		"www.oldwarwickians.org":["information", "school"],
		"www.northernperiphery.eu":["information", "government", "regional development"],
		"www.national-lottery.co.uk":["lifestyle", "gambling", "lottery"],
		"www.lakesidearts.org.uk":["lifestyle", "arts"],
		"www.johndcook.com":["support", "learning resources","statistics"],
		"www.indigoguide.com":["lifestyle", "travelling"],
		"www.iie.org":["information", "foundation", "international education"],
		"www.iggy.net":["information", "school"],
		"www.gradschools.com":["information", "courses", "graduate"],
		"www.gradfunding.co.uk":["information", "courses", "graduate funding"],
		"www.fxprodesign.co.uk":["support", "digital media", "web design"],
		"www.futurelearn.com":["support", "learning resources"],
		"www.fulbrightalumni.org.uk":["communication", "social network", "alumni"],
		"www.fatwallet.com":["support", "shopping", "cashback"],
		"www.esu.org":["information", "charity", "childrens education"],
		"www.econometricsbysimulation.com":["support", "learning resources", "econometrics"],
		"www.earnmydegree.com":["information", "courses","degree"],
		"www.dsprelated.com":["information", "news", "technology", "dsp"],
		"www.dspguide.com":["support", "learning resources", "digital signal processing"],
		"www.dianomioffers.co.uk":["support", "shopping"],
		"www.deccanherald.com":["information", "news"],
		"www.debatingmatters.com":["information", "schools", "debating"],
		"www.dnaindia.com":["information", "news"],
		"www.dailyreckoning.co.uk":["information", "news"],
		"www.crossref.org":["information", "academic"],
		"www.cottonmills.co.uk":["support", "accommodation"],
		"www.consortiumuk.net":["information", "university"],
		"www.conicyt.cl":["information", "academic"],
		"www.conacyt.mx":["information", "academic"],
		"www.chainreactioncycles.com":["support", "shopping", "bikes"],
		"www.bmj.com":["information", "academic", "medical"],
		"www.bis.org":["information", "finance",  "banking"],
		"www.birminghamrestaurantsandbars.com":["lifestyle", "food", "restaurant"],
		"www.atgtickets.com":["support", "tickets"],
		"www.asanet.org":["information", "academic", "sociology"],
		"www.altmetric.com":["information", "academic"],
		"www.alphr.com":["information", "news", "technology"],
		"www.aldi.co.uk":["support", "shopping","supermarket"],
		"www.888casino.com":["lifestyle", "gambling"],
		"worthwhile.typepad.com":["communication", "blog", "canadian economics"],
		"uk.mcafeestore.com":["support", "antivirus"],
		"thebmjawards.bmj.com":["information", "academic", "medical"],
		"store.office.com":["support", "shopping", "microsoft office"],
		"sophos.com":["support", "antivirus"],
		"outlook.office.com":["support", "shopping", "microsoft office"],
		"outdatedbrowser.com":["support", "tools", "browser version"],
		"onedrive.live.com":["support", "backups"],
		"masterclasses.bmj.com":["information", "courses","healthcare"],
		"journals.bmj.com":["information", "academic", "medical"],
		"gottwurfelt.com":["communication", "blog", "mathematician"],
		"geni.us":["support", "tools", "url shortener"],
		"fulbright.org.uk":["information", "educational exchange"],
		"foursquare.com":["communication", "social network"],
		"eranraviv.com":["communication", "blog", "econometrics and stats"],
		"dailyo.in":["entertainment", "magazine", "humour"],
		"charteredabs.org":["information", "business schools"],
		"bridgehousetheatre.co.uk":["lifestyle", "arts", "theatre"],
		"baltimore.eat24hours.com":["lifestyle", "food", "restaurant"],
		"marcfbellemare.com": ["communication", "blog", "agriculture"],
		"maltonyorkshire.co.uk":["lifestyle", "food", "food market"],
		"kaplan":["support", "learning resources"],
		"docs.google.com":["support", "backups", "documents"],
		"drive.google.com":["support", "backups"],
		"maps.google.com":["support", "travel"],
		"play.google.com":["support", "software", "apps"],
		"dating.independent.co.uk":["lifestyle", "dating"],
	},
	
	//best effort based on tokens in urls
	partial: {
		
		//communication
		
		"plus": ["communication", "social networking"],
		"facebook": ["communication", "social networking"],
		"linkedin": ["communication", "social networking"],
		"hangouts": ["communication", "social networking"],
		"twitter": ["communication", "social networking"],
		"pinterest": ["communication", "social networking"],
		"instagram": ["communication", "social networking", "photos"],
		"stumbleupon": ["communication", "social networking"],
		"yorkspace": ["communication", "social networking", "students"],
		"shelfari": ["communication", "social networking", "reading"],
		
		
		"flickr": ["communication", "images"],
		"tumblr": ["communication", "blog"],
		"blog": ["communication", "blog"],
		"wordpress": ["communication","blog"],
		"wp.com":["communication","blog"],
		"wp.me":["communication","blog"],
		"wp.pl":["communication","blog"],
		"gummy-stuff": ["communication","blog", "money"],
		"skype": ["communication", "conferencing"],
		"mail": ["communication", "email"],
		"email": ["communication", "email"],
		
		//information
		
		"stepstone": ["information", "jobs"],
		"adzuna": ["information", "jobs"],
		"reed.co.uk": ["information", "jobs"],
		"indeed": ["information", "jobs"],
		"job": ["information", "jobs"],
		"candidate": ["information", "jobs"],
		"career": ["information", "jobs"],
		"monster": ["information", "jobs"],
		"appointment": ["information", "jobs"],
		"recruit":["information", "jobs"],
		"hired": ["information", "jobs"],
		"milkround": ["information", "jobs"],
		"talent": ["information", "jobs"],
		"capgemini": ["information", "jobs"],
		"internships": ["information", "jobs"],
		"cebglobal":["information", "jobs"],
		"shl.com":["information", "jobs"],
		"workcircle": ["information", "jobs"],
		
		"experiencepg.com": ["information", "jobs"],
		"tutor":["information", "tutoring"],
		
		"ancestry":["information", "ancestry"],
		"masters": ["information", "courses", "masters"],
		"phd": ["information", "courses", "doctorate"],
		"mba": ["information", "courses", "mba"],
		"study" : ["information", "courses"],
		"doctorate": ["information", "courses", "doctorate"],
		"degrees": ["information", "courses", "degree"],
		"chances4.me": ["information", "courses"],
		
		"iggi.org.uk": ["information", "courses", "gaming"],
		
		"student": ["information", "university"],
		"graduate": ["information", "university"],
		".edu": ["information", "university"],
		".ac.uk": ["information", "university"],
		"ucas" : ["information", "university"],
		"uio.no": ["support", "university"],
		"ualberta.ca" :  ["support", "university"],
		"uni": ["information", "university"],
		
		
		
		"hrsummit": ["information", "conference", "human resources"],
		"inytartfortomorrow.com": ["information", "conference", "art"],
		
		"trustpilot": ["information", "reviews"],
		"reviews": ["information", "reviews"],
	
		
		
		"scribd": ["information", "books"],
		"library": ["information", "library"],
		"book": ["information", "books"],
		"scholar": ["information", "academic"],
		"wiley": ["information", "academic"],
		"science": ["information", "academic"],
		"academic": ["information", "academic"],
	
		
		
		"indiatimes": ["information", "news", "india"],
		"ibnlive": ["information", "news", "india"],
		"aajtak.in": ["information", "news", "india"],
		
		"news": ["information", "news"],
		"cnbc": ["information", "news"],
		"times": ["information", "news"],
		"post" : ["information", "news"],
		
		
		"consultancy.uk" : ["information", "news", "consultancy"],
	
		"wsj.com":["information", "news"],
		"wsj.net":["information", "news"],
		"theweek.co.uk":["information", "news"],
		"standard.co.uk": ["information", "news"],
		"news.bbc": ["information", "news"],
		"chronicle": ["information", "news"],
		"today" : ["information", "news"],
		"mirror" : ["information", "news"],
		"thesun" :  ["information", "news"],
		"reuters" : ["information", "news"],
		
		"independent.co.uk" :  ["information", "news"],
		"guardian": ["information", "news"],
		
		
		"telegraph": ["information", "news"],
		
		
		
		"gogreenindia":  ["information", "news", "conservation"],
		"who.int": ["information", "news", "world health"],
		
		"techinsider":["information", "news", "technology"],
		"techcrunch":["information", "news", "technology"],
		"techradar": ["information", "news", "technology"],
		"gizmodo": ["information", "news", "technology"],
		
		
		"cambridge":["information", "region", "cambridge"],
		
		"ey.com": ["information", "finance", "business"],
		"economic": ["information", "finance", "business"],
		"business": ["information", "finance", "business"],
		"forbes":["information", "finance", "business"],
		"bloomberg":["information", "finance", "business"],
		"biz":["information", "finance", "business"],
	
		
		"macquarie" : ["information", "finance", "investment"], 
		"brandcapital.co": ["information", "finance", "investment"], 
		"fidelity.com": ["information", "finance", "investment"], 
		"stocks": ["information", "finance", "investment"],
		"shares": ["information", "finance", "investment"],
		"invest": ["information","finance", "investment"],
		"market": ["information", "finance", "investment"],
		"wealth": ["information", "finance", "investment"],
		"trading": ["information", "finance", "investment"],
		"nikkei": ["information", "finance", "investment"],
		"bseindia.com": ["information", "finance", "investment"],
		"icidirect": ["information", "finance", "investment"],
		"hl.co.uk":["information", "finance", "investment"],
		
		"accenture": ["information", "consulting", "information technology"],
		
		"gs.com":["information", "finance",  "banking"],
		"goldman": ["information", "finance", "banking"],
		"jpmorgan": ["information", "finance", "banking"],
		"chase.com" : ["information", "finance", "banking"],
		"morganstanley": ["information", "finance", "banking"],
		"bankofengland": ["information", "finance", "banking"],
	
		"finan": ["information", "finance"],
		"ft.com": ["information", "finance"],
		"currency" : ["information", "finance"],
		"money":["information", "finance"],
		"weather": ["information", "weather"],
		
		"aicpa": ["information","finance", "accounting"],
		"icaew": ["information","finance", "accounting"],
		"cimaglobal": ["information","finance", "accounting"],
		"accountant": ["information", "finance", "accounting"],
		"accounting": ["information", "finance", "accounting"],
		"accountancy": ["information", "finance", "accounting"],
		"acca": ["information", "finance", "accounting"],
		"acfe":  ["information", "finance", "accounting"],
		"pwc": ["information", "finance", "accounting"],
	
	
		"cipd.co.uk":  ["information", "human resources"],
		
		"www.ihbc.org.uk": ["information", "building conservation"],
		 
		"youronlinechoices": ["information", "computers", "safety and privacy"],
		"cis-india": ["information", "computers", "society"],
		"programmer": ["information", "computers", "programming"],
		"apple": ["information", "computers", "hardware"],
		"windowsphone": ["information", "mobile"],
		"android": ["information", "mobile"],
		
		"health": ["lifestyle","health"],
		"clinic": ["lifestyle", "health"],
		"diabetes": ["lifestyle", "health", "diabetes"],
		"acne": ["lifestyle", "health", "acne"],
		
		"gov.uk": ["information", "government"],
		".gov": ["information", "government"],
		"insidegov": ["information", "government"],
		"publicnotices":["information", "local"],
		"public-notices":["information", "local"],
		"mathoverflow": ["communication", "forum", "maths"],
		
		"quora": ["communication" ,"forum"],
		"answers": ["communication", "forum"],
		"stackexchange":["communication", "forum"],
		"stackoverflow":["communication", "forum", "tech"],
		"serverfault": ["communication", "forum", "tech", "systems and networks"],
		"superuser": ["communication", "forum", "tech"],
		"askubuntu":["communication", "forum", "tech", "operating system"],
		
		"wiki":["information"],
		"reddit":["communication", "forum"],
	
		"dummies": ["information", "howto"],
		//support
		
		"delicious": ["support", "bookmarks"],
		
		"godaddy.com": ["support", "domain names"],
		"alivear":["support", "search engine"],
		"google.com" : ["support", "search engine"],
		"www.google.com": ["support", "search engine"],
		"www.google.co.uk": ["support", "search engine"],
		"www.google.co.in": ["support", "search engine"],
		"bing.com": ["support", "search engine"],
		"bing.co.uk": ["support", "search engine"],
		"www.yahoo.co.uk": ["support", "search engine"],
		"www.yahoo.com": ["support", "search engine"],
		"search.yahoo":["support", "search engine"],
		"aol.com": ["support", "search engine"],
		"info.yahoo": ["support", "search engine"],
		"ask.com": ["support", "search engine"],
		"mybrowserbar":["support", "search engine"],
	
		"energy": ["support", "energy"],
	
		"mediafire": ["support", "backups"],
		"icloud": ["support", "backups"],
		"dropbox": ["support", "backups", "documents"],
		"play.google": ["support", "software", "apps"],
		"survey": ["participation", "surveys"],
		"gwallet": ["support", "payment"],
	
		"doodle": ["support", "calendar"],
		"calendar": ["support", "calendar"],
	
		"translate": ["support", "translate"],
	
		"shop": ["support", "shopping"],
		"ebay": ["support", "shopping"],
		"asda": ["support", "shopping","supermarket"],
		"argos": ["support", "shopping"],
		"tesco": ["support", "shopping","supermarket"],
		"waitrose": ["support", "shopping", "supermarket"],
		"boots": ["support", "shopping", "pharmacy"],
		"amazon": ["support", "shopping"],
		"newlook": ["support", "shopping", "clothes"],
		"houseoffraser": ["support","shopping"],
		"dorothyperkins":  ["support","shopping"],
		
		"certum.pl":["support","shopping", "gadgets"], 
		
		"home": ["support", "property"],
		"fish4": ["support", "property"],
		"www.magicbricks.com": ["support", "property"],
		
		"dating" : ["lifestyle", "dating"],
		"simplymarry.com" : ["lifestyle", "dating"],
		"match.com" : ["lifestyle", "dating"],
		
		
		"barclays":["support", "bank"],
		"santander": ["support", "bank"],
		"lloyds":["support", "bank"],
		"natwest":["support", "bank"],
		"paypal":["support", "ecommerce"],
	 	"nwolb":["support", "bank"],
	 
	 	"hiscox.co.uk": ["support", "insurance"],
	 	
		"travel":["support", "travel"],
		"liverail":["support", "travel", "rail"],
		"air":["support", "travel", "air"],
		"map":["support", "travel"],
		"booking":["support", "travel"],
		"heathrow":["support", "travel", "airport"],
		"gatwick":["support", "travel", "airport"],
	
	
		"bbb.org": ["support", "recommendations", "businesses"],
		
		"accounts.google": ["support"],
		
		"coursera": ["support", "online course"],
		"saylor": ["support", "online course"],
		
		"scaledb" : ["support", "tools", "database"],
		"mongodb" : ["support", "tools", "database"],
		"srmo.sagepub" : ["support", "tools", "research"],
		"everesttech.net" : ["support", "tools", "creative"],
		"www.adobe.com" : ["support", "tools", "creative"],
		"printfriendly" : ["support", "tools", "printing"],
		"trustwave": ["support", "tools", "security"],
		"regressit": ["support", "tools", "stats"],
		"statmodel": ["support", "tools", "stats"],
		
		
		"grammarly": ["support", "writing"],
		"essay": ["support", "writing"],
		
		"idioms" : ["support", "language"],
		"eviews.com": ["support", "learning resources", "econometrics"],
		
		"liferichpublishing": ["support", "writing"],
		"markedbyteachers":  ["support", "writing"],
		"freelancewriters": ["support", "writing"],
		
		"getrevising": ["support", "coursework or exams"],
		"topperlearning": ["support", "coursework or exams"],
		
		"statistics" : ["support", "learning resources","statistics"],
		"robjhyndman": ["support", "learning resources","statistics"],
		"jeremyjaytaylor": ["support","learning resources", "statistics"],
		"statsmakemecry": ["support","learning resources", "statistics"],
		
		"price": ["support", "price comparison"],
		"theecoexperts.co.uk": ["support", "price comparison"],
		
		"profitaccumulator":  ["lifestyle", "gambling"],
		"gamble" : ["lifestyle", "gambling"],
		"gambling": ["lifestyle", "gambling"],
		"skybet" : ["lifestyle", "gambling"],
		
		"astro": ["lifestyle", "astrology"],
		
		//entertainment
		
		"workout": ["lifestyle", "health", "fitness"],
	
		"honestjohn": ["entertainment", "interest", "cars"],
		"carbuyer":  ["entertainment", "interest", "cars"],
		"fixmycar":  ["entertainment", "interest", "cars"],
		"motor": ["entertainment", "interest", "cars"],
		"wheels": ["entertainment", "interest", "cars"],
	
		"league": ["lifestyle", "sport"],
		"sport": ["lifestyle", "sport"],
		"football": ["lifestyle", "sport", "football"],
		"cricbuzz": ["lifestyle", "sport", "cricket"],
		"fashion": ["entertainment", "interest", "fashion"],
		"style": ["entertainment", "interest", "fashion"],
		"magazine.newlook": ["entertainment", "interest", "fashion"],
		
		"explorable.com": ["entertainment", "interest"],
		
		"viralmozo": ["entertainment", "interest", "celebrity"],
		"celebrity": ["entertainment", "interest", "celebrity"],
		"zoomtv": ["entertainment", "interest", "celebrity"],
		"peekworthy": ["entertainment", "interest", "celebrity"],
		
		"puzzle" :  ["entertainment", "interest", "puzzles"],
		
		"quirker":["entertainment", "magazine", "humour"],
		"dailymotion":["entertainment", "magazine", "humour"],
		"idistracted": ["entertainment", "magazine", "humour"],
		"mashable":["entertainment", "magazine", "humour"],
		"udderlypettable": ["entertainment", "magazine", "animals"],
		"pixte":["entertainment", "magazine"],
		"issuu.com": ["entertainment", "magazine"],
		"checkthisyo": ["entertainment", "magazine"],
		"smartlifeweekly": ["entertainment", "magazine"],
		
		
		"veryfacts": ["entertainment", "magazine", "womens"],
		"supersavvyme": ["entertainment", "magazine", "womens"],
		"idiva.com": ["entertainment", "magazine", "womens"],
		"cosmopolitan.in": ["entertainment", "magazine", "womens"],
		"cosmopolitan.com": ["entertainment", "magazine", "womens"],
		"wonderwoman": ["entertainment", "magazine", "womens"],
		
		"www.vice.com" :["entertainment", "magazine"],
		"readersdigest": ["entertainment", "magazine"],
		"rd.com": ["entertainment", "magazine"],
		"www.wired.co.uk":["entertainment", "magazine", "technology and design"],
		
		
	
		"flix" : ["entertainment", "streaming", "movies"],
		"video": ["entertainment", "films"],
		"movie": ["entertainment", "films"],
		"bollywood": ["entertainment", "films", "bollywood"],
		"bbc.com":["entertainment", "tv"],
		"historyindia":["entertainment", "tv"],
		".tv":["entertainment", "tv"],
		"youtube": ["entertainment", "streaming", "video"],
		
		"itv.com":["entertainment", "streaming", "video"],
		"vimeo" :["entertainment", "streaming", "video"],
		"ustream":["entertainment", "streaming", "video"],
		"music": ["entertainment", "streaming", "music"],
		"mp3": ["entertainment", "streaming", "music"],
		"tunes": ["entertainment", "streaming", "music"],
		"gaana": ["entertainment", "streaming", "music"],
		
		
	
		"film": ["entertainment", "films"],
		"game":  ["entertainment", "gaming"],
		"gaming": ["entertainment", "gaming"],
		"plarium": ["entertainment", "gaming"],
		"lilplay":["entertainment", "gaming"],
		"codebreaker.codes":["entertainment", "gaming"],
		
		"audible":["entertainment", "audiobook"],
		
		
		"mother" : [ "lifestyle", "parenthood"],
		"family" : ["lifestyle", "parenthood"],
		"parent" : ["lifestyle", "parenthood"],
		"child" : ["lifestyle", "parenthood"],
		
		"seriouseats": ["lifestyle", "food", "recipes"],
		"recipes": ["lifestyle", "food", "recipies"],
		"davesgourmet":   ["lifestyle", "food", "food product"],
		"croftersorganic": ["lifestyle", "food", "food product"],
		"dine" : ["lifestyle", "food"],
		"food" : ["lifestyle", "food"],
		"jusrol" : ["lifestyle", "food","food product"],
		"bellabdevans": ["lifestyle", "food","food product"],
		"bionaturae": ["lifestyle", "food","food product"],
		"sirkensingtons" : ["lifestyle", "food","food product"],
		"bobsredmill":  [ "lifestyle", "food","food product"],
		"colavita.com" : ["lifestyle", "food","food product"],
		"rodale": ["lifestyle", "food"],
		"nutiva" :["lifestyle", "food", "healthy eating"],
		"nutrition": ["lifestyle", "food", "healthy eating"],
		"chriskresser": ["lifestyle", "health"],
		"mindbodygreen": [ "lifestyle", "health"],
		"preventionpulse":  [ "lifestyle", "health"],
		
		"alternativedaily": [ "lifestyle", "health"],
		"interesticle" : ["lifestyle", "health"],
		"safeordangerous": ["lifestyle", "health"],
		
		"destination": [ "lifestyle", "travelling"],
		"lonelyplanet": [ "lifestyle", "travelling"],
		"4daysin": [ "lifestyle", "travelling"],
		"happytrips": [ "lifestyle", "travelling"],
		"holiday": [ "lifestyle", "travelling"],
		"secretescapes" : ["lifestyle", "travelling"],
	
		"lifehacker": ["lifestyle"],
	}
};