module.exports = 
{

	//full urls
	
	full: {
		"eyecareplus" : ["lifestyle", "health", "eyes"],
		"dating.birminghammail" : ["lifestyle", "dating"],
		"birminghammail": ["information", "news", "regional"],
		"mailcashback":["support", "shopping", "cashback"],
		"callforparticipants":["participation"],
		"visualdna":["participation", "profiling"],
		"ucnproject":["participation", "data collection"],
		"toluna":["participation", "surveys"],
		"yourword":["participation", "surveys"],
		"thinkindia":["participation", "policy", "indian"],
		
		"yougov.co.uk":["information", "government"],
		"ycharts.com":["support", "tools", "research", "financial"],
		"yandex.ru":["support", "search engine"],
		"yahoo.net":["support", "search engine"],
		"www2.smartbrief.com":["information", "news", "industry"],
		"www.zoneoneradio.com": ["entertainment", "streaming", "music"],
		"www.yoyo.com": ["support", "shopping","toys"],
		"www.wymans.com":["lifestyle", "food", "healthly eating"],
		"www.worldcat.org":["information", "library"],
		"www.weibo.com": ["communication", "blog"],
		"www.webcourseworks.com":["support", "learning resources"],
		"www.walmart.com":["support", "shopping", "supermarket"],
		"www.vocativ.com":["entertainment", "magazine", "technology and media"],
		"www.vasantvalley.org":["information", "school"],
		"www.ursongspk.com":["entertainment", "streaming", "music"],
		"www.ukcisa.org.uk":["information", "university", "international students"],
		"www.ubuonline.co.uk":["information", "university", "student union"],
		"www.trynewperfumes.com":["participation", "product sampling"],
		"www.trickybet.net": ["lifestyle", "gambling"],
		"www.trendingfirst.co.uk":["entertainment", "magazine", "technology and media"],
		"www.trademarkencyclopedia.com":["information", "trademarks"],
		"www.top-employers.com":["information", "jobs"],
		"www.timetobreak.com":["entertainment", "interest", "celebrity"],
		"www.thevalueperspective.co.uk":["information", "finance", "investment"], 
		"www.theflystudio.com":["support", "digital media", "web design"],
		"www.thecampusprogram.org":["support", "student", "mental health"],
		"www.thebrofessional.net":["entertainment", "interest", "celebrity"],
		"www.thebrightsidetrust.org":["support", "mentoring"],
		"www.theartisanbistro.com":["lifestyle", "food"],
		"www.the-network.com":["information", "jobs"],
		"www.tentopi.com":["entertainment", "interest", "celebrity"],
		"www.tedbakerplc.com":["support", "shopping", "clothes"],
		"www.tedbaker.com":["support", "shopping", "clothes"],
		"www.td.org":["information", "career development"],
		"www.tandfonline.com":["information", "academic"],
		"www.tagoras.com":["support", "learning resources"],
		"www.swlearning.com":["support", "learning resources"],
		"www.stockplanconnect.com":["support", "tools", "research", "financial"],
		"www.stata.com":["support", "tools", "stats"],
		"www.springer.com":["information", "academic"],
		"www.speakingtree.in":["lifestyle", "astrology"],
		"www.softworld.co.uk":["information", "jobs"],
		"www.smuckers.com":["lifestyle", "food"],
		"www.smartbrief.com":["information", "news", "industry"],
		"www.sipc.org":["information", "finance", "investment", "protection"],
		"www.simplyorganic.com":["lifestyle", "food"],
		"www.sikhi.sm":["lifestyle", "religion", "sikhism"],
		"www.sephora.com":["support", "shopping", "beauty"],
		"www.scopus.com":["information", "academic"],
		"www.schweser.com":["information", "courses", "financial certification"],
		"www.savingschampion.co.uk":["information", "money saving"],
		"www.saveur.com":["lifestyle", "food"],
		"www.sas.com":["support", "tools" , "analytics"],
		"www.sapub.org":["information", "academic"],
		"www.sadc.int":["information", "african development"],
		"www.riskglossary.com":["information", "finance", "risk"],
		"www.reports.dianomioffers.co.uk":["information", "reports"],
		"www.regalcreative.com":["support", "digital media"],
		"www.reedglobal.com":["information", "jobs"],
		"www.reedcommercial.com":["information", "jobs"],
		"www.redonline.co.uk":["entertainment", "magazine", "womens"],
		"www.rediff.com": ["information", "news", "india"],
		"www.realclearworld.com":["information", "news"],
		"www.realclear.com":["entertainment", "magazine", "humour"],
		"www.rd-india.com":["entertainment", "magazine"],
		"www.qtsnumeracytest.co.uk":["support", "tests", "numeracy"],
		"www.psychtesting.org.uk":["support", "tests", "psychometric"],
		"www.prweb.com":["information", "news", "public relations"],
		"www.prevention.com":["lifestyle", "health"],
		"www.placement-uk.com":["information", "placements"],
		"www.phpbb.com":["support", "tools", "bulletin board"],
		"www.pearsonschoolsandfecolleges.co.uk":["information", "courses"],
		"www.pearsonhighered.com":["information", "courses"],
		"www.pawsaminute.net":["entertainment", "interest", "dogs"],
		"www.passtheqtsskillstests.co.uk":["support", "tests", "qts"],
		"www.parisattitude.com":["support", "travel", "paris"],
		"www.paloalto.com":["support", "tools", "business planning"],
		"www.paidproducttesting.co.uk":["participation", "product sampling"],
		"www.paidfocusgroup.co.uk":["participation", "focus group"],
		"www.paconsulting.com":["information", "consulting"],
		"www.oyorooms.com":["support", "travel", "india"],
		"www.organicvalley.coop":["lifestyle", "food"],
		"www.orderannualreports.com":["information", "reports"],
		"www.onrec.com":["information", "jobs"],
		"www.nytwineclub.com":["lifestyle", "food", "wine"],
		"www.nytco.com":["information","news"],
		"www.nutsonline.org":["entertainment", "tv", "student tv"],
		"www.nseindia.com":["information", "finance", "investment"],
		"www.nottsvarsity.co.uk":["entertainment", "interest", "sport"],
		"www.nottinghamtec.co.uk":["information", "audio equipment"],
		"www.netetudes.com":["participation", "surveys"],
		"www.nasoya.com":["lifestyle", "food"],
		"www.nao.org.uk":["information", "finance", "auditing"],
		"www.myspace.com":["communication", "social networking"],
		"www.myhabit.com":["support", "shopping", "clothes"],
		"www.mydearvalentine.com":["lifestyle", "dating"],
		"www.mvmtwatches.com":["support", "shopping", "watches"],
		"www.msn.com":["support", "search engine"],
		"www.mrsite.com":["support", "tools", "website"],
		"www.mplans.com":["information", "marketing"],
		"www.moonflowerdesign.net":["support", "digital media", "web design"],
		"www.mooch-bar.co.uk":["lifestyle", "restaurant"],
		"www.momondo.co.uk":["communication", "blog"],
		"www.meridianks.com":["support", "learning resources"],
		"www.mercola.com":["lifestyle", "health"],
		"www.mercer.com":["information", "finance"],
		"www.maxwrapup.com":["entertainment", "magazine", "mens"],
		"www.mansionglobal.com":["lifestyle", "luxury property"],
		"www.macrothink.org":["information", "academic"],
		"www.m2k.me":["entertainment", "streaming", "films"],
		"www.lseg.com":["information", "finance", "investment"],
		"www.look.com":["support", "shopping", "childrens clothes"],
		"www.londonstockexchange.com":["information", "finance", "investment"],
		"www.londonperfect.com":["support", "travel", "paris"],
		"www.liveplans.com":["support", "tools", "business planning"],
		"www.liveplan.com":["support", "tools", "business planning"],
		"www.literallydarling.com":["entertainment", "magazine", "womens"],
		"www.kusumatrust.org":["information", "charity", "childrens education"],
		"www.kingarthurflour.com":["lifestyle", "food"],
		"www.karger.com":["information", "academic"],
		"www.junglee.com":["support", "classifieds"],
		"www.jstor.org":["information", "academic"],
		"www.jprime.com":["information", "finance", "investment"],
		"www.jlr.org":["information", "academic", "lipids"],
		"www.jlcre.com":["information", "finance", "realestate"],
		"www.jitsufoundation.org":["lifestyle", "fitness", "jiu jitsu"],
		"www.jefferies.com":["information", "finance", "investment"],
		"www.iza.org":["information", "academic", "labor"],
		"www.ivoryresearch.com":["support", "coursework or exams"],
		"www.ireland.com":["support", "travel", "ireland"],
		"www.ipoll.com":["participation", "surveys"],
		"www.iovs.org":["information", "academic", "opthalmology"],
		"www.intergrad.co.uk":["information", "jobs"],
		"www.insidehighered.com":["information", "news", "higher education"],
		"www.infobase.co.in":["support", "digital media", "web design"],
		"www.india-forums.com":["information", "forum"],
		"www.independentsubscriptions.co.uk":["information", "news"],
		"www.incisivemedia.com":["information", "finance", "business"],
		"www.impactnottingham.com":["entertainment", "magazine", "student union"],
		"www.imdb.com":["entertainment", "films"],
		"www.imanet.org":["information","finance", "accounting"],
		"www.hp.com": ["information", "computers", "hardware"],
		"www.hindawi.com":["information", "academic"],
		"www.highfliers.co.uk":["information", "jobs"],
		"www.hertfordshiremercury.co.uk": ["information", "news", "regional"],
		"www.hbrsasia.org":["misc"],
		"www.harpersbazaar.co.uk":["misc"],
		"www.graphpad.com":["misc"],
		"www.gq-magazine.co.uk":["misc"],
		"www.gossipedge.com":["misc"],
		"www.goodreads.com":["misc"],
		"www.golfdigestindia.com":["misc"],
		"www.gleems.com":["misc"],
		"www.glassdoor.co.uk":["misc"],
		"www.girlinlondon.com":["misc"],
		"www.geoplugin.net":["misc"],
		"www.gdst.net":["misc"],
		"www.gadgetsngizmos.in":["misc"],
		"www.fuzzfix.com":["misc"],
		"www.furl.net":["misc"],
		"www.ftse.com":["misc"],
		"www.fow.com":["misc"],
		"www.fotor.com":["misc"],
		"www.flavourjournal.com":["misc"],
		"www.findcpd.com":["misc"],
		"www.filepicker.io":["misc"],
		"www.fidelityinternational.com":["misc"],
		"www.fca.org.uk":["misc"],
		"www.famefocus.com":["misc"],
		"www.exinfm.com":["misc"],
		"www.eventbrite.co.uk":["misc"],
		"www.eurolines.co.uk":["misc"],
		"www.eurekaselect.com":["misc"],
		"www.espn.co.uk":["misc"],
		"www.emolument.com":["misc"],
		"www.elsevier.com":["misc"],
		"www.elearninglearning.com":["misc"],
		"www.efficientlearning.com":["misc"],
		"www.edenred.co.uk":["misc"],
		"www.economist.com":["misc"],
		"www.econometrics.com":["misc"],
		"www.e2eresearch.com":["misc"],
		"www.dpreview.co.uk":["misc"],
		"www.diva-portal.org":["misc"],
		"www.directions.org.uk":["misc"],
		"www.dipintosales.co.uk":["misc"],
		"www.digitalistmag.com":["misc"],
		"www.diapers.com":["misc"],
		"www.dianomi.com":["misc"],
		"www.deshaw.com":["misc"],
		"www.deepdyve.com":["misc"],
		"www.db.com":["misc"],
		"www.danahotyoga.com":["misc"],
		"www.dailyo.in":["misc"],
		"www.crystalski.co.uk":["misc"],
		"www.createspace.co.uk":["misc"],
		"www.crainsnewyork.com":["misc"],
		"www.cpareviewforfree.com":["misc"],
		"www.coursework4you.co.uk":["misc"],
		"www.coursehero.com":["misc"],
		"www.copyright.com":["misc"],
		"www.convertiblebonds.ch":["misc"],
		"www.cmo.com":["misc"],
		"www.cloudy.ec":["misc"],
		"www.cloudpro.co.uk":["misc"],
		"www.civicuk.com":["misc"],
		"www.city-data.com":["misc"],
		"www.citeulike.org":["misc"],
		"www.cimaondemand.com":["misc"],
		"www.cii.co.uk":["misc"],
		"www.chicmodern.co.uk":["misc"],
		"www.chevening.org":["misc"],
		"www.cheapflights.ca":["misc"],
		"www.channelpro.co.uk":["misc"],
		"www.cgma.org":["misc"],
		"www.cfainstitute.org":["misc"],
		"www.capco.com":["misc"],
		"www.c2c-online.co.uk":["misc"],
		"www.buzzaura.com":["misc"],
		"www.buyvip.com":["misc"],
		"www.burton.co.uk":["misc"],
		"www.brightknowledge.org":["misc"],
		"www.breadcreative.com":["misc"],
		"www.bplans.com":["misc"],
		"www.bp.com":["misc"],
		"www.bg-removals.co.uk":["misc"],
		"www.bellandevans.com":["misc"],
		"www.bdo.com":["misc"],
		"www.bazaarvoice.com":["misc"],
		"www.barneys.com":["misc"],
		"www.bap.org":["misc"],
		"www.aviva.co.uk":["misc"],
		"www.attractiontix.co.uk":["misc"],
		"www.assignmentwritinghelp.com":["misc"],
		"www.ascentive.com":["misc"],
		"www.aquarico.com":["misc"],
		"www.apartmenttherapy.com":["misc"],
		"www.apa.org":["misc"],
		"www.aon.com":["misc"],
		"www.aon.co.uk":["misc"],
		"www.aon-onboarding.co.uk":["misc"],
		"www.angloamerican.com":["misc"],
		"www.analystforum.com":["misc"],
		"www.amosweb.com":["misc"],
		"www.amd.com":["misc"],
		"www.ahzassociates.co.uk":["misc"],
		"www.agcas.org.uk":["misc"],
		"www.acx.com":["misc"],
		"www.activeminds.org":["misc"],
		"www.activebeat.com":["misc"],
		"www.accidentadvicehelpline.co.uk":["misc"],
		"www.aabri.com":["misc"],
		"www.aabestemployer.co.uk":["misc"],
		"www.123helpme.com":["misc"],
		"wu.ac.at":["misc"],
		"weheartit.com":["misc"],
		"watching.zentrick.com":["misc"],
		"wanderingpioneer.com":["misc"],
		"voteview.com":["misc"],
		"vitamind.mercola.com":["misc"],
		"viralvinny.com":["misc"],
		"vine.co":["misc"],
		"viewmixed.com":["misc"],
		"vidshare.us":["misc"],
		"vaccines.mercola.com":["misc"],
		"uwasa.fi":["misc"],
		"unrulymedia.com":["misc"],
		"uk.yahoo.com":["misc"],
		"uk.screen.yahoo.com":["misc"],
		"uk.safely.yahoo.com":["misc"],
		"uk.mobile.yahoo.com":["misc"],
		"uk.messenger.yahoo.com":["misc"],
		"uk.mercer.com":["misc"],
		"uk.help.yahoo.com":["misc"],
		"uk.groups.yahoo.com":["misc"],
		"uk.everything.yahoo.com":["misc"],
		"uk.easyroommate.com":["misc"],
		"uk.dice.com":["misc"],
		"uberhavoc.com":["misc"],
		"uam.es":["misc"],
		"tradefx.com":["misc"],
		"tmdb.org":["misc"],
		"thirtythreeweb.co.uk":["misc"],
		"thetab.com":["misc"],
		"theologyphilosophycentre.co.uk":["misc"],
		"thelocalpeople.co.uk":["misc"],
		"theconversation.com":["misc"],
		"thebigchoice.com":["misc"],
		"tablesorter.com":["misc"],
		"suitcasemag.com":["misc"],
		"stumble-upon.com":["misc"],
		"stockfuse.com":["misc"],
		"statext.com":["misc"],
		"squarespace.com":["misc"],
		"soletshangout.com":["misc"],
		"software.instant-income-app.com":["misc"],
		"snoutit.com":["misc"],
		"sniperlog.ru":["misc"],
		"smmc.squarespace.com":["support", "statistics"],
		"smartclip.net":["misc"],
		"silktide.com":["misc"],
		"sharemasterindia.com":["misc"],
		"semcs.net":["misc"],
		"sellfy.com":["misc"],
		"securetrk.co.uk":["misc"],
		"sciverse.com":["misc"],
		"schoolleavers.mazars.co.uk":["misc"],
		"sayedhossain.com":["misc"],
		"sappartneredge.com":["misc"],
		"sap.com":["misc"],
		"qz.com":["misc"],
		"psl.com":["misc"],
		"principlesofeconometrics.com":["misc"],
		"preventionindia.in":["misc"],
		"prbb.org":["misc"],
		"polldaddy.com":["misc"],
		"planningcommission.nic.in":["misc"],
		"pes.org.ph":["misc"],
		"pardot.com":["misc"],
		"pages.rediff.com":["misc"],
		"owlgraphic.com":["misc"],
		"ow.ly":["misc"],
		"orders.edenred.co.uk":["misc"],
		"ordering.edenred.co.uk":["misc"],
		"openload.co":["misc"],
		"olinwustl.campusgroups.com":["misc"],
		"nytedu.com":["misc"],
		"nyt.com":["misc"],
		"nxbus.co.uk":["misc"],
		"nuclersoncanthinger.info":["misc"],
		"nottingham.us8.list-manage2.com":["misc"],
		"nottingham.us7.list-manage.com":["misc"],
		"northcliffedigital.co.uk":["misc"],
		"nomnompaleo.com":["misc"],
		"nlreg.com":["misc"],
		"newtheatre.org.uk":["misc"],
		"mypage.rediff.com":["misc"],
		"msecnd.net":["misc"],
		"mixpanel.com":["misc"],
		"metro.co.uk":["misc"],
		"mercury.mercola.com":["misc"],
		"mazars.co.uk":["misc"],
		"mathworld.wolfram.com":["misc"],
		"mandrillapp.com":["misc"],
		"mackeeper.com":["misc"],
		"luxurybeyondproduct.com":["misc"],
		"livesimply.me":["misc"],
		"lipas.uwasa.fi":["misc"],
		"letwatch.us":["misc"],
		"learneconometrics.com":["misc"],
		"labs.rediff.com":["misc"],
		"kerrygoldusa.com":["misc"],
		"karalydon.com":["misc"],
		"isu.pub":["misc"],
		"ishare.rediff.com":["misc"],
		"instant-income-app.com":["misc"],
		"inkandwater.co.uk":["misc"],
		"independent.touchlocal.com":["misc"],
		"imworld.rediff.com":["misc"],
		"images.tedbakerimages.com":["misc"],
		"hubspot.com":["misc"],
		"hrlabhost.co.uk":["misc"],
		"hereisthecity.com":["misc"],
		"greatist.com":["misc"],
		"gfk.com":["misc"],
		"gazefree.com":["misc"],
		"fullthrottlelegends.com":["misc"],
		"fructose.mercola.com":["misc"],
		"freshstartineducation.co.uk":["misc"],
		"fluoride.mercola.com":["misc"],
		"flatworldknowledge.com":["misc"],
		"fitness.mercola.com":["misc"],
		"fidelity.co.uk":["misc"],
		"events.qz.com":["misc"],
		"europa.eu":["misc"],
		"esri.com":["misc"],
		"elearningfeeds.com":["misc"],
		"ejbe.org":["misc"],
		"do-it.org":["misc"],
		"distillery.wistia.com":["misc"],
		"digg.com":["misc"],
		"dice.com":["misc"],
		"creativecommons.org":["misc"],
		"corporate.morningstar.com":["misc"],
		"cookieandkate.com":["misc"],
		"conviva.com":["misc"],
		"compensationinsider.com":["misc"],
		"commerce.rediff.com":["misc"],
		"clients.rediff.com":["misc"],
		"chachisays.net":["misc"],
		"catalog.flatworldknowledge.com":["misc"],
		"cancer.mercola.com":["misc"],
		"campus.bankofamerica.com":["misc"],
		"brightoninteractive.com":["misc"],
		"bragg.com":["misc"],
		"borsaitaliana.it":["misc"],
		"boreburn.com":["misc"],
		"bodyos.me":["misc"],
		"blueimp.github.io":["misc"],
		"bham.hobsons.co.uk":["misc"],
		"bakingbites.com":["misc"],
		"aw.com":["misc"],
		"articles.mercola.com":["misc"],
		"articles.bplans.com":["misc"],
		"apester.com":["misc"],
		"animalmozo.com":["misc"],
		"alphatrk.com":["misc"],
		"alltop.com":["misc"],
		"adventurecrunch.com":["misc"],
		"aaapubs.org":["misc"],
	},
	
	//best effort based on tokens in urls
	partial: {
		
		//communication
		
		"plus": ["communication", "social networking"],
		"facebook": ["communication", "social networking"],
		"linkedin": ["communication", "social networking"],
		"hangouts": ["communication", "social networking"],
		"twitter": ["communication", "social networking"],
		"pinterest": ["communication", "social networking"],
		"instagram": ["communication", "social networking"],
		"stumbleupon": ["communication", "social networking"],
		"yorkspace": ["communication", "social networking", "students"],
		"shelfari": ["communication", "social networking", "book"],
		
		
		"flickr": ["communication", "images"],
		"tumblr": ["communication", "blog"],
		"blog": ["communication", "blog"],
		"wordpress": ["communication","blog"],
		"wp.com":["communication","blog"],
		"wp.me":["communication","blog"],
		"wp.pl":["communication","blog"],
		"gummy-stuff": ["communication","blog", "money"],
		"skype": ["communication", "conferencing"],
		"mail": ["communication", "email"],
		"email": ["communication", "email"],
		
		//information
		
		"stepstone": ["information", "jobs"],
		"adzuna": ["information", "jobs"],
		"reed.co.uk": ["information", "jobs"],
		"indeed": ["information", "jobs"],
		"job": ["information", "jobs"],
		"candidate": ["information", "jobs"],
		"career": ["information", "jobs"],
		"monster": ["information", "jobs"],
		"appointment": ["information", "jobs"],
		"recruit":["information", "jobs"],
		"hired": ["information", "jobs"],
		"milkround": ["information", "jobs"],
		"talent": ["information", "jobs"],
		"capgemini": ["information", "jobs"],
		"internships": ["information", "jobs"],
		"cebglobal":["information", "jobs"],
		"shl.com":["information", "jobs"],
		"workcircle": ["information", "jobs"],
		
		"experiencepg.com": ["information", "jobs"],
		"tutor":["information", "tutoring"],
		
		"ancestry":["information", "ancestry"],
		"masters": ["information", "courses"],
		"phd": ["information", "courses"],
		"mba": ["information", "courses"],
		"study" : ["information", "courses"],
		"doctorate": ["information", "courses"],
		"degrees": ["information", "courses"],
		"chances4.me": ["information", "courses"],
		
		"iggi.org.uk": ["information", "courses", "gaming"],
		
		"student": ["information", "university"],
		"graduate": ["information", "university"],
		".edu": ["information", "university"],
		".ac.uk": ["information", "university"],
		"ucas" : ["information", "university"],
		"uio.no": ["support", "university"],
		"ualberta.ca" :  ["support", "university"],
		"uni": ["information", "university"],
		
		
		
		"hrsummit": ["information", "conference", "human resources"],
		"inytartfortomorrow.com": ["information", "conference", "art"],
		
		"trustpilot": ["information", "reviews"],
		"reviews": ["information", "reviews"],
	
		
		
		"scribd": ["information", "books"],
		"library": ["information", "library"],
		"book": ["information", "books"],
		"scholar": ["information", "academic"],
		"wiley": ["information", "academic"],
		"science": ["information", "academic"],
		"academic": ["information", "academic"],
	
		
		
		"indiatimes": ["information", "news", "india"],
		"ibnlive": ["information", "news", "india"],
		"aajtak.in": ["information", "news", "india"],
		
		"news": ["information", "news"],
		"cnbc": ["information", "news"],
		"times": ["information", "news"],
		"press": ["information", "news"],
		"post" : ["information", "news"],
		
		
		"consultancy.uk" : ["information", "news", "consultancy"],
	
		"wsj.com":["information", "news"],
		"wsj.net":["information", "news"],
		"theweek.co.uk":["information", "news"],
		"standard.co.uk": ["information", "news"],
		"news.bbc": ["information", "news"],
		"chronicle": ["information", "news"],
		"today" : ["information", "news"],
		"mirror" : ["information", "news"],
		"thesun" :  ["information", "news"],
		"reuters" : ["information", "news"],
		"independent.co.uk" :  ["information", "news"],
		"guardian": ["information", "news"],
		"telegraph": ["information", "news"],
		
		
		
		"gogreenindia":  ["information", "news", "conservation"],
		"who.int": ["information", "news", "world health"],
		
		"techinsider":["information", "news", "technology"],
		"techcrunch":["information", "news", "technology"],
		"techradar": ["information", "news", "technology"],
		"gizmodo": ["information", "news", "technology"],
		
		
		"cambridge":["information", "region", "cambridge"],
		
		"ey.com": ["information", "finance", "business"],
		"economic": ["information", "finance", "business"],
		"business": ["information", "finance", "business"],
		"forbes":["information", "finance", "business"],
		"bloomberg":["information", "finance", "business"],
		"biz":["information", "finance", "business"],
	
		
		"macquarie" : ["information", "finance", "investment"], 
		"brandcapital.co": ["information", "finance", "investment"], 
		"fidelity.com": ["information", "finance", "investment"], 
		"stocks": ["information", "finance", "investment"],
		"shares": ["information", "finance", "investment"],
		"invest": ["information","finance", "investment"],
		"market": ["information", "finance", "investment"],
		"wealth": ["information", "finance", "investment"],
		"trading": ["information", "finance", "investment"],
		"nikkei": ["information", "finance", "investment"],
		"bseindia.com": ["information", "finance", "investment"],
		"icidirect": ["information", "finance", "investment"],
		"hl.co.uk":["information", "finance", "investment"],
		
		"accenture": ["information", "consulting", "information technology"],
		
		"gs.com":["information", "finance",  "banking"],
		"goldman": ["information", "finance", "banking"],
		"jpmorgan": ["information", "finance", "banking"],
		"chase.com" : ["information", "finance", "banking"],
		"morganstanley": ["information", "finance", "banking"],
		"bankofengland": ["information", "finance", "banking"],
	
		"finan": ["information", "finance"],
		"ft.com": ["information", "finance"],
		"currency" : ["information", "finance"],
		"money":["information", "finance"],
		"weather": ["information", "weather"],
		
		"aicpa": ["information","finance", "accounting"],
		"icaew": ["information","finance", "accounting"],
		"cimaglobal": ["information","finance", "accounting"],
		"accountant": ["information", "finance", "accounting"],
		"accounting": ["information", "finance", "accounting"],
		"accountancy": ["information", "finance", "accounting"],
		"acca": ["information", "finance", "accounting"],
		"acfe":  ["information", "finance", "accounting"],
		"pwc": ["information", "finance", "accounting"],
	
	
		"cipd.co.uk":  ["information", "human resources"],
		
		"www.ihbc.org.uk": ["information", "building conservation"],
		 
		"youronlinechoices": ["information", "computers", "privacy"],
		"cis-india": ["information", "computers", "society"],
		"programmer": ["information", "computers", "programming"],
		"apple": ["information", "computers", "hardware"],
		"windowsphone": ["information", "mobile"],
		"android": ["information", "mobile"],
		
		"health": ["information","health"],
		"clinic": ["information", "health"],
		"diabetes": ["information", "health", "diabetes"],
		"acne": ["information", "health", "acne"],
		
		"gov.uk": ["information", "government"],
		".gov": ["information", "government"],
		"insidegov": ["information", "government"],
		"publicnotices":["information", "local"],
		"public-notices":["information", "local"],
		"mathoverflow": ["information", "forum", "maths"],
		
		"quora": ["information", "forum"],
		"answers": ["information", "forum"],
		"stackexchange":["information", "forum"],
		"stackoverflow":["information", "forum", "tech"],
		"serverfault": ["information", "forum", "tech", "systems and networks"],
		"superuser": ["information", "forum", "tech"],
		"askubuntu":["information", "forum", "tech", "operating system"],
		
		"wiki":["information"],
		"reddit":["information", "forum"],
	
		"dummies": ["information", "howto"],
		//support
		
		"delicious": ["support", "bookmarks"],
		
		"godaddy.com": ["support", "domain names"],
		"alivear":["support", "search engine"],
		"google.com" : ["support", "search engine"],
		"www.google.com": ["support", "search engine"],
		"www.google.co.uk": ["support", "search engine"],
		"www.google.co.in": ["support", "search engine"],
		"bing.com": ["support", "search engine"],
		"bing.co.uk": ["support", "search engine"],
		"www.yahoo.co.uk": ["support", "search engine"],
		"www.yahoo.com": ["support", "search engine"],
		"search.yahoo":["support", "search engine"],
		"aol.com": ["support", "search engine"],
		"info.yahoo": ["support", "search engine"],
		"ask.com": ["support", "search engine"],
		"mybrowserbar":["support", "search engine"],
	
		"energy": ["support", "energy"],
	
		"mediafire": ["support", "backups"],
		"icloud": ["support", "backups"],
		"dropbox": ["support", "backups", "documents"],
		"play.google": ["support", "software", "apps"],
		"survey": ["participation", "surveys"],
		"gwallet": ["support", "payment"],
	
		"doodle": ["support", "calendar"],
		"calendar": ["support", "calendar"],
	
		"translate": ["support", "translate"],
	
		"shop": ["support", "shopping"],
		"ebay": ["support", "shopping"],
		"asda": ["support", "shopping","supermarket"],
		"argos": ["support", "shopping"],
		"tesco": ["support", "shopping","supermarket"],
		"waitrose": ["support", "shopping", "supermarket"],
		"boots": ["support", "shopping", "pharmacy"],
		"amazon": ["support", "shopping"],
		"newlook": ["support", "shopping", "clothes"],
		"houseoffraser": ["support","shopping"],
		"dorothyperkins":  ["support","shopping"],
		
		"certum.pl":["support","shopping", "gadgets"], 
		
		"home": ["support", "property"],
		"fish4": ["support", "property"],
		"www.magicbricks.com": ["support", "property"],
		
		"dating" : ["lifestyle", "dating"],
		"simplymarry.com" : ["lifestyle", "dating"],
		"match.com" : ["lifestyle", "dating"],
		
		
		"barclays":["support", "bank"],
		"santander": ["support", "bank"],
		"lloyds":["support", "bank"],
		"natwest":["support", "bank"],
		"paypal":["support", "bank"],
	 	"nwolb":["support", "bank"],
	 
	 	"hiscox.co.uk": ["support", "insurance"],
	 	
		"travel":["support", "travel"],
		"liverail":["support", "travel"],
		"air":["support", "travel"],
		"map":["support", "travel"],
		"booking":["support", "travel"],
		"heathrow":["support", "travel"],
		"gatwick":["support", "travel"],
	
	
		"bbb.org": ["support", "recommendations", "businesses"],
		
		"accounts.google": ["support"],
		
		"coursera": ["support", "online course"],
		"saylor": ["support", "online course"],
		
		"scaledb" : ["support", "tools", "database"],
		"mongodb" : ["support", "tools", "database"],
		"srmo.sagepub" : ["support", "tools", "research"],
		"everesttech.net" : ["support", "tools", "creative"],
		"www.adobe.com" : ["support", "tools", "creative"],
		"printfriendly" : ["support", "tools", "printing"],
		"trustwave": ["support", "tools", "security"],
		"regressit": ["support", "tools", "stats"],
		"statmodel": ["support", "tools", "stats"],
		
		
		"grammarly": ["support", "writing"],
		"essay": ["support", "writing"],
		
		"idioms" : ["support", "language"],
		"eviews.com": ["support", "econometrics"],
		
		"liferichpublishing": ["support", "writing"],
		"markedbyteachers":  ["support", "writing"],
		"freelancewriters": ["support", "writing"],
		
		"getrevising": ["support", "coursework or exams"],
		"topperlearning": ["support", "coursework or exams"],
		
		"statistics" : ["support", "statistics"],
		"robjhyndman": ["support", "statistics"],
		"jeremyjaytaylor": ["support", "statistics"],
		"statsmakemecry": ["support", "statistics"],
		
		"price": ["support", "price comparison"],
		"theecoexperts.co.uk": ["support", "price comparison"],
		
		"profitaccumulator":  ["lifestyle", "gambling"],
		"gamble" : ["lifestyle", "gambling"],
		"gambling": ["lifestyle", "gambling"],
		"skybet" : ["lifestyle", "gambling"],
		
		"astro": ["lifestyle", "astrology"],
		
		//entertainment
		
		"workout": ["entertainment", "fitness"],
	
		"honestjohn": ["entertainment", "interest", "cars"],
		"carbuyer":  ["entertainment", "interest", "cars"],
		"fixmycar":  ["entertainment", "interest", "cars"],
		"motor": ["entertainment", "interest", "cars"],
		"wheels": ["entertainment", "interest", "cars"],
	
		"league": ["entertainment", "interest", "sport"],
		"sport": ["entertainment", "interest", "sport"],
		"football": ["entertainment", "interest", "sport", "football"],
		"cricbuzz": ["entertainment", "interest", "sport", "cricket"],
		"fashion": ["entertainment", "interest", "fashion"],
		"style": ["entertainment", "interest", "fashion"],
		"magazine.newlook": ["entertainment", "interest", "fashion"],
		
		"explorable.com": ["entertainment", "interest", "research"],
		
		"viralmozo": ["entertainment", "interest", "celebrity"],
		"celebrity": ["entertainment", "interest", "celebrity"],
		"zoomtv": ["entertainment", "interest", "celebrity"],
		"peekworthy": ["entertainment", "interest", "celebrity"],
		
		"puzzle" :  ["entertainment", "interest", "puzzles"],
		
		"quirker":["entertainment", "magazine", "humour"],
		"dailymotion":["entertainment", "magazine", "humour"],
		"idistracted": ["entertainment", "magazine", "humour"],
		"mashable":["entertainment", "magazine", "humour"],
		"udderlypettable": ["entertainment", "magazine", "humour", "animals"],
		"pixte":["entertainment", "magazine"],
		"issuu.com": ["entertainment", "magazine"],
		"checkthisyo": ["entertainment", "magazine"],
		"smartlifeweekly": ["entertainment", "magazine"],
		
		
		"veryfacts": ["entertainment", "magazine", "womens"],
		"supersavvyme": ["entertainment", "magazine", "womens"],
		"idiva.com": ["entertainment", "magazine", "womens"],
		"cosmopolitan.in": ["entertainment", "magazine", "womens"],
		"cosmopolitan.com": ["entertainment", "magazine", "womens"],
		"wonderwoman": ["entertainment", "magazine", "womens"],
		
		"www.vice.com" :["entertainment", "magazine"],
		"readersdigest": ["entertainment", "magazine"],
		"rd.com": ["entertainment", "magazine"],
		"www.wired.co.uk":["entertainment", "magazine", "technology and design"],
		
		
	
		"flix" : ["entertainment", "streaming", "films"],
		"video": ["entertainment", "films"],
		"movie": ["entertainment", "films"],
		"bollywood": ["entertainment", "films", "bollywood"],
		"bbc.com":["entertainment", "tv"],
		"historyindia":["entertainment", "tv"],
		".tv":["entertainment", "tv"],
		"youtube": ["entertainment", "streaming", "video"],
		
		"itv.com":["entertainment", "streaming", "video"],
		"vimeo" :["entertainment", "streaming", "video"],
		"ustream":["entertainment", "streaming", "video"],
		"music": ["entertainment", "streaming", "music"],
		"mp3": ["entertainment", "streaming", "music"],
		"tunes": ["entertainment", "streaming", "music"],
		"gaana": ["entertainment", "streaming", "music"],
		
		
	
		"film": ["entertainment", "films"],
		"game":  ["entertainment", "gaming"],
		"gaming": ["entertainment", "gaming"],
		"plarium": ["entertainment", "gaming"],
		"lilplay":["entertainment", "gaming"],
		"codebreaker.codes":["entertainment", "gaming"],
		
		"audible":["entertainment", "audiobook"],
		
		
		"mother" : [ "lifestyle", "parenthood"],
		"family" : ["lifestyle", "parenthood"],
		"parent" : ["lifestyle", "parenthood"],
		"child" : ["lifestyle", "parenthood"],
		
		"seriouseats": ["lifestyle", "food"],
		"recipes": ["lifestyle", "food"],
		"davesgourmet":   ["lifestyle", "food"],
		"croftersorganic": ["lifestyle", "food"],
		"dine" : ["lifestyle", "food"],
		"food" : ["lifestyle", "food"],
		"jusrol" : ["lifestyle", "food"],
		"bellabdevans": ["lifestyle", "food"],
		"bionaturae": ["lifestyle", "food"],
		"sirkensingtons" : ["lifestyle", "food"],
		"bobsredmill":  [ "lifestyle", "food"],
		"colavita.com" : ["lifestyle", "food"],
		"nutiva" :["lifestyle", "food", "healthly eating"],
		"nutrition": ["lifestyle", "food", "healthly eating"],
		"chriskresser": ["lifestyle", "health"],
		"mindbodygreen": [ "lifestyle", "health"],
		"preventionpulse":  [ "lifestyle", "health"],
		
		"alternativedaily": [ "lifestyle", "health"],
		"interesticle" : ["lifestyle", "health"],
		"safeordangerous": ["lifestyle", "health"],
		
		"destination": [ "lifestyle", "travelling"],
		"lonelyplanet": [ "lifestyle", "travelling"],
		"4daysin": [ "lifestyle", "travelling"],
		"happytrips": [ "lifestyle", "travelling"],
		"holiday": [ "lifestyle", "travelling"],
		"secretescapes" : ["lifestyle", "travelling"],
	
		"lifehacker": ["lifestyle"],
	}
};