export const ActionTypes= {
	CATEGORY_DATA:'CATEGORY_DATA',
	HISTOGRAM_DATA:'HISTOGRAM_DATA',
	DURATION_DATA:'DURATION_DATA',
	NODE_SELECTED:'NODE_SELECTED',
	URL_SELECTED:'URL_SELECTED',
	DEVICE_SELECTED:'DEVICE_SELECTED',
	DEVICES_DATA:'DEVICES_DATA',
	ZONES_DATA:'ZONES_DATA',
	ROUTINE_DATA:'ROUTINE_DATA',
	ROUTINE_ZONE_DATA:'ROUTINE_DATA',
	ROUTINE_TOGGLE_BROWSING:'ROUTINE_TOGGLE_BROWSING',
	ROUTINE_TOGGLE_CATEGORIES:'ROUTINE_TOGGLE_CATEGORIES',
	ZONE_SELECTED:'ZONE_SELECTED',
	FULL_CATEGORIES:'FULL_CATEGORIES',
	
};